apiVersion: v1
name: harbor-scanner-trivy
version: 0.34.0
appVersion: 0.34.0
description: Harbor scanner adapter for Trivy
keywords:
  - scanner
  - harbor
  - vulnerability
sources:
- https://github.com/goharbor/harbor-scanner-trivy
